#-------------------------- HTTP output ------------------------------
#output.http:
#    hosts: ["${STSURL}connbeat?api_key=${"]
#
# Optional further settings:
#    protocol: "https"
#    path: "foo"
#    parameters: "xyz"
#    proxy_url: "xyz"
#    loadbalance: true
#    compression_level: 9
#    max_retries: 3
#    timeout: 90 seconds
#    headers:
#      Content-Type: application/json
#      X-API-Key: abcdefghijklmnop...
#    bufferMinInterval: 10   # Min number of seconds before buffered events are POSTed
#    bufferMaxInterval: 30   # Max number of seconds before buffered events are POSTed
#    bufferCount: 2          # Number of events to buffer before POSTing
#    tls:
#        enabled: false
#        verification_mode: "full"
#        supported_protocols: [...]
#        cipher_suites: [...]
#        curve_types: [...]
#        certificate_authorities: [...]
#        certificate: ...
#        key: ...
#        key_passphrase: ...
#
# BASIC authentication:
#    username: "alice"
#    password: "secret"
